name: "show-inputs"

on:
  push:
    branches:
      - "main"

jobs:
  show-environment-inputs-without-input-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/main-action
        with:
          DATA: 'Why do I see this under INPUT_DATA within the container?'
          QUERY: 'If the with parameter is creating the input vars whether or not they are in the action.yaml,'
          QUERY_CONT: ' then is the action.yaml only for metadata purposes when the action is published?'